# Generated by Django 5.2.1 on 2025-05-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipes",
            "0006_alter_favorite_options_alter_shoppingcart_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "default_related_name": "favorites",
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранные",
            },
        ),
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "default_related_name": "shopping_carts",
                "verbose_name": "Корзина",
                "verbose_name_plural": "Корзина",
            },
        ),
    ]
