name: flake8 Lint

on:
  push:
    paths:
      - 'backend/**/*.py'
      - 'setup.conf'
      - '.github/workflows/flake8.yml'
  pull_request:
    paths:
      - 'backend/**/*.py'
      - 'setup.conf'
      - '.github/workflows/flake8.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.13']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # если есть backend/requirements.txt — установим
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
          pip install flake8==7.*

      - name: Run flake8
        run: flake8 --config setup.conf backend
